[package]
name = "ocpi-tariffs-cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tandemdrive/ocpi-tariffs"

[[bin]]
name = "ocpi-tariffs"
path = "src/main.rs"

[dependencies]
clap.workspace = true
ocpi-tariffs.workspace = true
thiserror.workspace = true
serde_json.workspace = true
tabled = { version = "0.10.0", features = ["color"] }
chrono-tz.workspace = true
colored.workspace = true
